# remove: version: "3.9"

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: fintrack
      POSTGRES_USER: finuser
      POSTGRES_PASSWORD: finpass
    ports: ["5433:5432"]
    volumes: ["pgdata:/var/lib/postgresql/data"]

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    environment: { ZOOKEEPER_CLIENT_PORT: 2181, ZOOKEEPER_TICK_TIME: 2000 }

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    ports: [ "9092:9092" ]
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on: [ zookeeper ]


  mailhog:
    image: mailhog/mailhog:latest
    ports: ["1025:1025","8025:8025"]

volumes:
  pgdata:
